### ISSUE TITLE
Remove or change the wrong JAVA_HOME configuration in /etc/spark/conf/spark-env.sh

### ISSUE THREAD

**Issue by yanghua** [awesome-kyuubi/hadoop-testing#13]
The wrong config is [here](https://github.com/awesome-kyuubi/hadoop-testing/blob/master/hadoop-master1/files/etc/spark/conf/spark-env.sh#L1C27-L1C27).

It is used by `spark-submit`:

```shell
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.2.2
      /_/

Using Scala version 2.12.15 (OpenJDK 64-Bit Server VM, Java 17.0.9)
Type in expressions to have them evaluated.
Type :help for more information.
```

**Comment by yanghua** [comment]
cc @pan3793

**Comment by pan3793** [comment]
Yea, we should use java8 by default for consistent, it was used to test the spark 4.0-snapshot

**Comment by pan3793** [comment]
BTW, Spark supports Java 17 since 3.3

**Comment by yanghua** [comment]
> BTW, Spark supports Java 17 since 3.3 and requires at least Java 17 since 4.0

Got it. Currently, I fall back to Java 8 to take care of other components in the Hadoop ecosystem.

**Comment by pan3793** [comment]
yea, using Java8 by default makes sense, let's remove the JAVA_HOME overriding in `spark-defaults.conf`
