### ISSUE TITLE
Add kafka component into hadoop-testing

### ISSUE THREAD

**Issue by yanghua** [awesome-kyuubi/hadoop-testing#8]

**Comment by yanghua** [comment]
Hi @pan3793 Which version of Kafka do you prefer? The latest?

**Comment by pan3793** [comment]
Kafka does not couple with the Hadoop ecosystem, and the client's compatibility is good. Any version greater than 2.0 is good to me.

**Comment by yanghua** [comment]
> Kafka does not couple with the Hadoop ecosystem, and the client's compatibility is good. Any version greater than 2.0 is good to me.

I'd like to choose 2.8.2(the last version of 2.x series.)

**Comment by pan3793** [comment]
the last version of 2.x series SGTM :)

**Comment by yanghua** [comment]
> > Kafka does not couple with the Hadoop ecosystem, and the client's compatibility is good. Any version greater than 2.0 is good to me.
> 
> I'd like to choose 2.8.2(the last version of 2.x series.)

seems did not find the 2.8.2, finally I chose 2.8.1.
