### ISSUE TITLE
nc: can't connect to remote host (192.168.228.4): Connection refused

### ISSUE THREAD

**Issue by ocean-zhc** [awesome-kyuubi/hadoop-testing#90]
<img width="1794" alt="image" src="https://github.com/awesome-kyuubi/hadoop-testing/assets/46189785/5060ba8b-6f36-4618-bd0a-676e2e7d65e5">

After the Docker Compose Up is started, it has the following errors to see the log. It runs the container through orbstack, but it cannot be accessed through the domain name

**Comment by pan3793** [comment]
> it cannot be accessed through the domain name

Both Docker Desktop and OrbStack should be good to access other containers through the domain name in container, you can log in to a container and rung `ping hadoop-worker1.orb.local` to verify it.

the error message is expected, HDFS requires some init work, e.g. format namenode, create some dirs, and other services will wait for HDFS service ready by detecting some ports or files marks, after all pre-works ready, the service start

**Comment by pan3793** [comment]
BTW, all services in `hadoop-master*` and `hadoop-worker*` are managed through supervisor, you can run `supervisorctl status` to check the service status, and check logs under `/var/log/`

**Comment by ocean-zhc** [comment]
that's ok! tks!
